### ISSUE TITLE
Extend StateHook type to implement IWatchable

### ISSUE THREAD

**Issue by alexisvincent** [roman01la/uix#28]
Locally, I've extended StateHook to implement IWatchable to implement cursors over atoms, any chance this would be accepted into main?

**Comment by roman01la** [comment]
I was thinking more about this and decided to not go this way. React's state hook applies updates asynchronously, which means that current UIx state hook wrapped into an atom doesn't actually work as normal atom.

```clj
(let [s (uix/state 0)]
  (swap! s inc) ;; schedule state update
  @s) ;; still 0, until next re-render
```

There's no easy way to know when a value was actually applied, so no way to trigger watchers.

Instead of relying on watchers a cursor can be built using existing API:

```clj
(deftype Cursor [ref path]
  IDeref
  (-deref [o]
    (get-in @ref path))
  IReset
  (-reset! [o new-value]
    (swap! ref update-in path (constantly new-value)))

(defn derive-state [ref path]
  (uix/memo #(Cursor. ref path) [ref path]))

(let [state (uix/state {:idx 0})
      idx (derive-state state [:idx])]
  @idx)
```

I won't put this into the core since I've started working on a separate library for state management https://github.com/roman01la/uix/blob/master/core/src/xframe/core/alpha.cljc

**Comment by alexisvincent** [comment]
It would be interesting to have a chat about what your thoughts are in this area. I'm about to start working on a small state management system based on hooks, but trying to mitigate some of the reusability issues we hit in reframe.

My thoughts at the moment are to have a hybrid system that pulls some of the database logic from fulcro and expose simple endpoints in a hook based world, as well as more powerful but local "atom" based api. 

I'm curious to hear what your goals are, and what you want to reproduce/drop from the reframe world.

**Comment by roman01la** [comment]
I don't have experience with Fulcro. My goal for now to get closer to re-frame, but also keep it simple. I'm pretty happy with subscriptions graph, event and fx handlers, perhaps will add interceptors at some point.

Could you tell more about reusability issues you are hitting with re-frame?

**Comment by roman01la** [comment]
Closing this for now, please reopen if needed

**Comment by ava-sig** [comment]
love what you’ve done with xframe and with uix overall!
