### ISSUE TITLE
Passing state hook to child components

### ISSUE THREAD

**Issue by crofty** [roman01la/uix#30]
Firstly, thanks very much for the library, I've enjoyed using it a lot 👍 

**Describe the bug**
Since af4183104938f3c51775b7014435a2f58c7d438d I can no longer pass a state hook to a child component.  Previously I had been passing some hooks into child components and the child could manipulate the state.

**Include minimal repro**
```.cljs
(defn app []
  (let [value* (uix/state "")]
    [:div
     [:h1 "UIX issue"]
     [:div
      [:label "Input 1"]
      [:input
       {:type :text
        :value @value*
        :on-change #(reset! value* (.. % -target -value))}]]
     [:div
      [:label "Input 2"]
      [input value*]]
     [:p
      "Using commit 40e9adf74cf21163b15e5c57d1325675809bac19, these inputs work in the same way, typing in either will update the state stored in value*"]
     [:p
      "From commit af4183104938f3c51775b7014435a2f58c7d438d onwards, the inputs behave differently."]]))
```

**Expected behavior**
I would expect to be able to pass state hooks to children rather then needing to pass down the deferenced value and a callback.

**Comment by roman01la** [comment]
Seems like the issue you are describing is actually about child component not being updated because of memoization and reference type state hook, right?

This is expected behavior. Passing mutable references is not a good practice, instead pass a callback that takes care of updating the state. If you still want memoization to work, you'll also need to cache the callback using `callback` hook ([see React docs](https://reactjs.org/docs/hooks-reference.html#usecallback) for reference)

```clj
(let [value* (uix.core/state "")
      on-change (uix.core/callback #(swap! value* %) [@value*])]
  [child {:value @value* :on-change on-change}])
```

**Comment by crofty** [comment]
Yeah, that's the issue.  I was hoping that it'd that still be possible to pass the state hooks around as it's sometimes more convenient then passing callbacks.  If it's not good practice though I'll do the refactoring instead.
Thanks!

**Comment by roman01la** [comment]
I understand that passing ref type directly seems to be more convenient, but to make this work we'd need to disable memoization, which is super useful is a presence of immutable collections. There's also downsides of having memoization turned on by default, see #7
