### ISSUE TITLE
Benchmarks against Rum on the JVM

### ISSUE THREAD

**Issue by DjebbZ** [roman01la/uix#4]
Hello @roman01la ! Long time no Github issues :)

First of all, I've just discovered your library, which might be what we need to to move from Rum/Citrus to modern and more efficient React wrapper. I need to evaluate it more, and if it fits the bill, expect contributions from me as usual :)

I was just wondering that it could be nice to have a benchmark against Rum on the JVM itself.

Have a nice day !

**Comment by roman01la** [comment]
Hey hey 😂 JVM renderer is shamelessly stolen from Rum, so expect it to be on par with Rum. There's also streaming renderer, but it's using the same rendering code. Are you experiencing performance issues with Rum's serializer?

**Comment by DjebbZ** [comment]
Not especially, but I was expecting that moving from Rum to UIx wouldn't cause a performance regression. Having it "proved" via some benchmark would be nice. Don't you think?

**Comment by roman01la** [comment]
Sure. I don't know what's the best way to benchmark SSR, do you want to take care of this?

**Comment by DjebbZ** [comment]
Could be a good way to get into the code base. I don't know either, maybe rum already does something similar ?

**Comment by roman01la** [comment]
Indeed, looks like there's something already in Rum's repo https://github.com/tonsky/rum/blob/gh-pages/perf/rum/perf.clj

**Comment by DjebbZ** [comment]
Could basically copy-paste the code and replace `hiccup` with `uix`.

**Comment by roman01la** [comment]
Yep, I'll look into this soon. Let's see how it goes :)

**Comment by roman01la** [comment]
Ok, you got me. It was terribly slow because I missed a couple type hints :)
UIx is still ~10-15% slower than Rum, I suppose because of extended Hiccup parser that supports more syntax, but not sure.

**Comment by roman01la** [comment]
There's also a different point to think about: In Rum component is used as a function call `(button)`, which means when rendered on JVM a call to the root component immediately expands into the whole Hiccup tree. But UIx follows Reagent-style components usage pattern `[button]` where component is used in a Hiccup form rather than function call.

This means that when UIx components are rendered on JVM you don't get entire Hiccup tree immediately, instead serializer takes care of this. It can recognize a component (it's a function) as it traverses the tree and calls them to get deeper into the tree.

It doesn't seem to change the end result, but intermediate function calls could make a difference I guess. On the other hand Rum components also functions that would be called as Hiccup tree expands, the only difference is when they are called: during serialization as in UIx or before serialization as in Rum.

**Comment by DjebbZ** [comment]
So benchmarking was a good idea :)

Thanks for the insight about the inner workings of UIx. Does it mean it's
not possible to get the UI tree as a pure data structure since components
are not function calls?

**Comment by roman01la** [comment]
Yes, that's right. It has to be traversed and every function component usage site replaced with its return value. This way you can get the whole UI tree as a data structure. uix's UI tree is kind of a lazy data structure in a sense.

**Comment by roman01la** [comment]
Adding benchmark results in case someone would be interested in future

| lib | test 1 | test 2 | test 3 |
|--  |--        |--        |--         |
| rum | 107.8 µs | 3.6 ms | 7.7 ms |
| uix | 120.8 µs | 3.8 ms | 8.1 ms |
| uix streaming | 115.7 µs | 3.4 ms | 7.6 ms |
| hiccup | 205.7 µs | 6.5 ms | 16.6 ms |

**Comment by roman01la** [comment]
Should we close this issue?

**Comment by DjebbZ** [comment]
Sure
