### ISSUE TITLE
lazy_loader computes js module name from cljs namespace in an overly restrictive way

### ISSUE THREAD

**Issue by hammonba** [roman01la/uix#74]
`lazy_loader/require-lazy` is opinionated about how to derive js module name from cljs namespace.
This opinion is inconvenient to my namespace structure
```                 
module (->> (str lib)
                             (re-find #"\.([a-z0-9-]+)")
                             second
                             keyword)]
```

**Describe the solution you'd like**
I would be happy if I could pass the js module name in to the `require-lazy` macro,
but I understand that Roman has a more far-reaching solution in mind

**Comment by roman01la** [comment]
Here's an approach I have in mind that doesn't depend on your build tooling

```clojure
;; uix.core
(defn lazy
  "`f` is a promise returning function"
  [f]
  (react/lazy #(.then (f) (fn [component] #js {:default component}))))

;; application code when using shadow-cljs
;; cljc
(ns app.module-loader
  (:require [shadow.lazy])
  #?(:cljs (:require-macros [app.module-loader])))

#?(:clj
  (defmacro load+ [var-name-sym]
       `(shadow.lazy/load (shadow.lazy/loadable ~var-name-sym))))

;; application code, usage
;; cljs
(def lazy-button
  (uix.core/lazy #(app.module-loader/load+ app.ui.button)))
```

Basically UIx provides a thin wrapper around `react/lazy` and then it's up to you how to consume it. To simplify things further for you UIx could provide the macro for diff build tools via dedicated namespaces `uix.loader.shadow`, `uix.loader.figwheel`, etc. so that you'll end up writing only the following

```clojure
(def lazy-button
  (uix.core/lazy #(uix.loader.shadow/load+ app.ui.button)))
```

**Comment by roman01la** [comment]
The above is when you want to lazy load React components. Otherwise just use what your build tool provides, since it's not a concern for UIx.
